version: '3.8'
services:
  # ===== BASE DE DATOS =====
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-foro_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cambiar_este_password}
      POSTGRES_DB: ${POSTGRES_DB:-forumDB}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - foro_postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-foro_user} -d ${POSTGRES_DB:-forumDB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - foro_network

  # ===== PGBOUNCER =====
  pgbouncer:
    image: pgbouncer/pgbouncer:latest
    restart: unless-stopped
    environment:
      DATABASES_HOST: postgres
      DATABASES_PORT: 5432
      DATABASES_USER: ${POSTGRES_USER:-foro_user}
      DATABASES_PASSWORD: ${POSTGRES_PASSWORD:-cambiar_este_password}
      DATABASES_DBNAME: ${POSTGRES_DB:-forumDB}
      POOL_MODE: transaction
      MAX_CLIENT_CONN: 1000
      DEFAULT_POOL_SIZE: 30
      MIN_POOL_SIZE: 10
      AUTH_TYPE: scram-sha-256
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - foro_network

  # ===== MIGRACIONES AUTOMÁTICAS =====
  migrations:
    image: alexzafra13/foro-api:latest
    environment:
      - POSTGRES_DIRECT_URL=postgresql://${POSTGRES_USER:-foro_user}:${POSTGRES_PASSWORD:-cambiar_este_password}@postgres:5432/${POSTGRES_DB:-forumDB}
      - NODE_ENV=production
    depends_on:
      postgres:
        condition: service_healthy
    command: ["npx", "prisma", "migrate", "deploy"]
    networks:
      - foro_network
    restart: "no"

  # ===== SEED DE DATOS INICIALES =====
  seed:
    image: alexzafra13/foro-api:latest
    environment:
      - POSTGRES_DIRECT_URL=postgresql://${POSTGRES_USER:-foro_user}:${POSTGRES_PASSWORD:-cambiar_este_password}@postgres:5432/${POSTGRES_DB:-forumDB}
      - NODE_ENV=development
    depends_on:
      - migrations
    command: ["npm", "run", "db:seed"]
    networks:
      - foro_network
    restart: "no"

  # ===== FORO API =====
  foro-api:
    image: alexzafra13/foro-api:latest
    restart: unless-stopped
    ports:
      - "${API_PORT:-9090}:3000"
    environment:
      - POSTGRES_URL=postgresql://${POSTGRES_USER:-foro_user}:${POSTGRES_PASSWORD:-cambiar_este_password}@pgbouncer:6432/${POSTGRES_DB:-forumDB}
      - POSTGRES_DIRECT_URL=postgresql://${POSTGRES_USER:-foro_user}:${POSTGRES_PASSWORD:-cambiar_este_password}@postgres:5432/${POSTGRES_DB:-forumDB}
      - JWT_SECRET=${JWT_SECRET:-jwt_secret_CAMBIAR_EN_PRODUCCION_123456789}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
      - EMAIL_VERIFICATION_SECRET=${EMAIL_VERIFICATION_SECRET:-email_secret_CAMBIAR_123456789}
      - BCRYPT_ROUNDS=${BCRYPT_ROUNDS:-12}
      - MAILER_SERVICE=${MAILER_SERVICE:-gmail}
      - MAILER_EMAIL=${MAILER_EMAIL:-noreply@localhost}
      - MAILER_SECRET_KEY=${MAILER_SECRET_KEY:-dummy_password}
      - PORT=3000
      - NODE_ENV=production
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000,http://localhost:9090}
      - ENABLE_QUERY_LOGGING=false
      - CONNECTION_POOL_SIZE=30
    depends_on:
      - seed
      - pgbouncer
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    networks:
      - foro_network

volumes:
  foro_postgres_data:
    driver: local

networks:
  foro_network:
    driver: bridge